meta:
    /home/groups/CEDAR/estabroj/experiments/causal-path-pipeline/data/phospho_beta_meta.txt

# Column in {meta} to generate contrasts and correlation based networks 
condition:
    Condition

#  Phosphoproteomic dataset of columns [ID, Symbols, Sites, Effect, sample1, sample2, etc]
phos_prot:
    /home/groups/CEDAR/estabroj/experiments/causal-path-pipeline/data/phospho_prot_robust_z_new.txt

rna_file:
    /home/groups/CEDAR/estabroj/experiments/causal-path-pipeline/data/expression_file.txt

# permutations-for-significance : This parameter indicates the number of randomizations to perform. Recommended value: 1000
perm:
    100

# fdr-threshold-for-data-significance : The false discovery rate for network significance calculations for the downstream activity enrichment of genes. 
fdr:
    0.25

# site-match-proximity-threshold : When we observe a change in a site of the target protein which is not targeted by the relation, but the site is very close to a known target site of the relation, this parameter let's us to assume that the relation also applies to those close-by sites of within {site_match} of the known relation
site_match:
    1

# site-effect-proximity-threshold : CausalPath has a database of phosphorylation site effects. When not set, this parameter is 0 by default, which means exact usage of site effects. But sometimes we may see a site with unknown effect is modified, which is very close to another site with a known effect. This parameter let's us to assume those changing sites with unknown effect has the same effect with the neighbor site with known effect.
site_effect:
    1

# threshold-for-data-significance: A threshold value for selecting significant data. Use this parameter only when FDR controlling procedure is already performed outside of CausalPath. This parameter can be set for each different data type separately. The parameter value has to be in the form 'thr-val data-type', such like '1 phosphoprotein' or '2 protein.
ds_thresh:
    2.0
